### ISSUE TITLE
long time to show sources after eclipse restart

### ISSUE THREAD

**Issue by ifedorenko** [ifedorenko/com.ifedorenko.m2e.sourcelookup#14]
It takes very long time (minutes) to show the sources the first breakpoint hit after eclipse restart. There is no UI indication of anything running, progress view shows nothing, no busy cursor, etc. Operating system shows Eclipse uses one CPU core. jstack shows the following "interesting" stacktrace.  

~~~~
"Worker-112" #1242 prio=5 os_prio=31 tid=0x0000000138ae4000 nid=0x1425f runnable [0x0000000141eff000]
   java.lang.Thread.State: RUNNABLE
	at sun.security.provider.DigestBase.implCompressMultiBlock(DigestBase.java:140)
	at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:127)
	at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:580)
	at java.security.MessageDigest.update(MessageDigest.java:325)
	at com.google.common.hash.MessageDigestHashFunction$MessageDigestHasher.update(MessageDigestHashFunction.java:143)
	at com.google.common.hash.AbstractByteHasher.putBytes(AbstractByteHasher.java:77)
	at com.google.common.hash.AbstractByteHasher.putBytes(AbstractByteHasher.java:36)
	at com.google.common.hash.Funnels$SinkAsStream.write(Funnels.java:256)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:173)
	at com.google.common.io.ByteSource.copyTo(ByteSource.java:228)
	at com.google.common.io.ByteSource.hash(ByteSource.java:281)
	at com.google.common.io.Files.hash(Files.java:777)
	at com.ifedorenko.m2e.sourcelookup.internal.Locations.hash(Locations.java:18)
	at com.ifedorenko.m2e.sourcelookup.internal.Locations.hash(Locations.java:31)
	at com.ifedorenko.m2e.sourcelookup.internal.JavaProjectSources$JavaProjectInfo.<init>(JavaProjectSources.java:61)
	at com.ifedorenko.m2e.sourcelookup.internal.JavaProjectSources.addJavaProject(JavaProjectSources.java:183)
	at com.ifedorenko.m2e.sourcelookup.internal.JavaProjectSources.initialize(JavaProjectSources.java:147)
	- locked <0x00000007a13a6920> (a com.ifedorenko.m2e.sourcelookup.internal.JavaProjectSources$1)
	at com.ifedorenko.m2e.sourcelookup.internal.SourceLookupActivator.getWorkspaceSources0(SourceLookupActivator.java:87)
	- locked <0x00000007998cc858> (a com.ifedorenko.m2e.sourcelookup.internal.SourceLookupActivator)
	at com.ifedorenko.m2e.sourcelookup.internal.SourceLookupActivator.getWorkspaceSources(SourceLookupActivator.java:78)
	at com.ifedorenko.m2e.sourcelookup.internal.SourceLookupParticipant.getSourceContainer(SourceLookupParticipant.java:131)
	- locked <0x00000007998ecee0> (a java.util.HashMap)
	at com.ifedorenko.m2e.sourcelookup.internal.SourceLookupParticipant.findSourceElements(SourceLookupParticipant.java:94)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:142)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:505)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:785)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:344)
	- locked <0x00000007a12a68b0> (a org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$LRU)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:741)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
~~~~

Source lookup is fast after initial delay.

At very least need to provide some visual cues that Eclipse is busy doing stuff. Ideally with proper progress monitor. Better yet, make it faster and survive Eclipse restarts.

**Comment by ifedorenko** [comment]
fixed in 1.2.x, primarily commits 690731be8480d9e69483604913532f904a13171d and 69eccce8c4c6e1855ff82124c9daf3d0b9266ec0.
